services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "if [ '$$ENVIRONMENT' = 'production' ]; then uvicorn app.main:app --host 0.0.0.0 --port 8000; else uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload; fi"]
    working_dir: /app
